#!/usr/bin/env python3
"""Genera un .pptx de prueba 'sucio' a partir de una presentación real:
propiedades, propiedades personalizadas, miniatura, lista de personas con
cuenta e información de autores de comentarios.
Uso: make_fixture_pptx.py base.pptx salida.pptx
"""
import io
import sys
import zipfile

from PIL import Image

P = 'http://schemas.openxmlformats.org/presentationml/2006/main'
CT_NS = 'http://schemas.openxmlformats.org/package/2006/content-types'
RELS_NS = 'http://schemas.openxmlformats.org/package/2006/relationships'

CORE = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"'
    ' xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"'
    ' xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    '<dc:title>Propuesta comercial 2026</dc:title>'
    '<dc:subject>Presentaci\u00f3n para cliente</dc:subject>'
    '<dc:creator>Ariadna Betsab\u00e9 Mart\u00ednez Andrade</dc:creator>'
    '<cp:keywords>propuesta, cliente</cp:keywords>'
    '<dc:description>generated by python-pptx</dc:description>'
    '<cp:lastModifiedBy>ari martinez</cp:lastModifiedBy>'
    '<cp:revision>9</cp:revision>'
    '<dcterms:created xsi:type="dcterms:W3CDTF">2026-09-18T00:17:00Z</dcterms:created>'
    '<dcterms:modified xsi:type="dcterms:W3CDTF">2026-09-18T02:16:00Z</dcterms:modified>'
    '</cp:coreProperties>'
)

APP = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"'
    ' xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
    '<Template>Normal.potm</Template><TotalTime>87</TotalTime>'
    '<Company>Despacho Jur\u00eddico X</Company><Manager>Ariadna Mart\u00ednez</Manager>'
    '<Application>Microsoft PowerPoint</Application></Properties>'
)

CUSTOM = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties"'
    ' xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
    '<property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="_AuthorEmail">'
    '<vt:lpwstr>ari@ejemplo.com</vt:lpwstr></property></Properties>'
)

PERSONS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<p:personList xmlns:p="http://schemas.microsoft.com/office/powerpoint/2018/8/main"'
    ' xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">'
    '<p:person id="{11111111-2222-3333-4444-555555555555}"'
    ' displayName="Ariadna Mart\u00ednez" userId="bbf90fce0664e5a7" providerId="Windows Live"/>'
    '</p:personList>'
)

COMMENT_AUTHORS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    f'<p:cmLst xmlns:p="{P}">'
    '<p:cmAuthor id="0" name="Ariadna Mart\u00ednez" initials="AM" lastIdx="1" clrIdx="0"/>'
    '<p:cmAuthor id="1" name="ari martinez" initials="am" lastIdx="1" clrIdx="1"/>'
    '</p:cmLst>'
)


def thumbnail_jpeg():
    buf = io.BytesIO()
    Image.new('RGB', (32, 24), (200, 60, 60)).save(buf, 'JPEG', quality=70)
    return buf.getvalue()


def main(base, dst):
    with zipfile.ZipFile(base) as z:
        parts = [(i.filename, z.read(i.filename)) for i in z.infolist()]

    extra = {
        'docProps/core.xml': CORE.encode('utf-8'),
        'docProps/app.xml': APP.encode('utf-8'),
        'docProps/custom.xml': CUSTOM.encode('utf-8'),
        'docProps/thumbnail.jpeg': thumbnail_jpeg(),
        'ppt/persons/person.xml': PERSONS.encode('utf-8'),
        'ppt/commentAuthors.xml': COMMENT_AUTHORS.encode('utf-8'),
    }

    out = []
    for name, data in parts:
        if name in extra:
            continue
        text = data.decode('utf-8') if name.endswith(('.xml', '.rels')) else None
        if name == '_rels/.rels':
            text = text.replace('</Relationships>',
                                '<Relationship Id="rIdC" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/custom-properties"'
                                ' Target="docProps/custom.xml"/>'
                                '<Relationship Id="rIdT" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/thumbnail"'
                                ' Target="docProps/thumbnail.jpeg"/></Relationships>')
            data = text.encode('utf-8')
        elif name == 'ppt/_rels/presentation.xml.rels':
            text = text.replace('</Relationships>',
                                '<Relationship Id="rIdPers" Type="http://schemas.microsoft.com/office'
                                '/2019/09/relationships/person" Target="persons/person.xml"/>'
                                '<Relationship Id="rIdCm" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/commentsAuthors"'
                                ' Target="commentAuthors.xml"/></Relationships>')
            data = text.encode('utf-8')
        elif name == '[Content_Types].xml':
            for part, ctype in [
                ('/docProps/custom.xml',
                 'application/vnd.openxmlformats-officedocument.custom-properties+xml'),
                ('/docProps/thumbnail.jpeg', 'image/jpeg'),
                ('/ppt/persons/person.xml', 'application/vnd.ms-powerpoint.person+xml'),
                ('/ppt/commentAuthors.xml',
                 'application/vnd.openxmlformats-officedocument.presentationml.commentAuthors+xml'),
            ]:
                text = text.replace('</Types>',
                                    f'<Override PartName="{part}" ContentType="{ctype}"/></Types>')
            data = text.encode('utf-8')
        out.append((name, data))

    out.extend(extra.items())

    with zipfile.ZipFile(dst, 'w', zipfile.ZIP_DEFLATED) as zout:
        for name, data in out:
            info = zipfile.ZipInfo(name, date_time=(2026, 9, 18, 2, 30, 6))
            info.compress_type = zipfile.ZIP_DEFLATED
            zout.writestr(info, data)
    print('fixture pptx:', dst, len(out), 'partes')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
