#!/usr/bin/env python3
"""Construye un .docx de prueba 'sucio' inyectando todas las variantes de
metadatos que el limpiador debe retirar: control de cambios con autor y fecha,
comentarios, people.xml, propiedades personalizadas, rsid/paraId/docId, y
core/app.xml con datos personales.
Uso: make_fixture_dirty.py base.docx _fixture_sucio.docx
"""
import sys
import zipfile

W = 'http://schemas.openxmlformats.org/wordprocessingml/2006/main'
W15 = 'http://schemas.microsoft.com/office/word/2012/wordml'
CT_NS = 'http://schemas.openxmlformats.org/package/2006/content-types'
RELS_NS = 'http://schemas.openxmlformats.org/package/2006/relationships'

A1, D1 = 'Ariadna Mart\u00ednez', '2026-09-17T19:59:00Z'
A2, D2 = 'ari martinez', '2026-09-17T20:01:00Z'

INS = (f'<w:ins w:id="101" w:author="{A1}" w:date="{D1}">'
       '<w:r><w:t xml:space="preserve">TEXTO INSERTADO DE PRUEBA. </w:t></w:r></w:ins>')
DEL = (f'<w:del w:id="102" w:author="{A2}" w:date="{D2}">'
       '<w:r><w:delText xml:space="preserve">TEXTO BORRADO DE PRUEBA. </w:delText></w:r></w:del>')
PPR_CHANGE = (f'<w:pPrChange w:id="103" w:author="{A1}" w:date="{D1}">'
              '<w:pPr><w:ind w:left="0"/></w:pPr></w:pPrChange>')
RPR_CHANGE = (f'<w:rPrChange w:id="104" w:author="{A2}" w:date="{D2}">'
              '<w:rPr><w:b/></w:rPr></w:rPrChange>')
COMMENT_ANCHOR_START = '<w:commentRangeStart w:id="1"/>'
COMMENT_ANCHOR_END = ('<w:commentRangeEnd w:id="1"/><w:r><w:rPr>'
                      '<w:rStyle w:val="CommentReference"/></w:rPr>'
                      '<w:commentReference w:id="1"/></w:r>')

PEOPLE = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    f'<w15:people xmlns:w15="{W15}">'
    f'<w15:person w15:author="{A1}"><w15:presenceInfo w15:providerId="Windows Live"'
    ' w15:userId="bbf90fce0664e5a7"/></w15:person>'
    f'<w15:person w15:author="{A2}"><w15:presenceInfo w15:providerId="Windows Live"'
    ' w15:userId="04293925dad62832"/></w15:person></w15:people>'
)

COMMENTS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    f'<w:comments xmlns:w="{W}">'
    f'<w:comment w:id="1" w:author="{A1}" w:date="{D1}" w:initials="AM">'
    '<w:p><w:r><w:t>Revisar este p\u00e1rrafo antes de presentar.</w:t></w:r></w:p>'
    '</w:comment></w:comments>'
)

CUSTOM = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties"'
    ' xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
    '<property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="_AuthorEmail">'
    '<vt:lpwstr>ari@ejemplo.com</vt:lpwstr></property>'
    '<property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="3" name="Departamento">'
    '<vt:lpwstr>Jur\u00eddico</vt:lpwstr></property></Properties>'
)

CORE = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"'
    ' xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"'
    ' xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    '<dc:title>Conceptos de violaci\u00f3n</dc:title>'
    '<dc:subject>Demanda de amparo indirecto contra la sentencia dictada en el toca penal 122/2026</dc:subject>'
    '<dc:creator>Ariadna Betsab\u00e9 Mart\u00ednez Andrade</dc:creator>'
    '<cp:keywords>amparo indirecto, control preventivo, detenci\u00f3n</cp:keywords>'
    '<dc:description>generated by python-docx</dc:description>'
    '<cp:lastModifiedBy>ari martinez</cp:lastModifiedBy>'
    '<cp:revision>27</cp:revision>'
    '<dcterms:created xsi:type="dcterms:W3CDTF">2026-09-18T00:17:00Z</dcterms:created>'
    '<dcterms:modified xsi:type="dcterms:W3CDTF">2026-09-18T02:16:00Z</dcterms:modified>'
    '<cp:category/></cp:coreProperties>'
)

APP = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"'
    ' xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
    '<Template>Normal.dotm</Template><TotalTime>52</TotalTime><Company>Despacho Jur\u00eddico X</Company>'
    '<Manager>Ariadna Mart\u00ednez</Manager><Application>Microsoft Office Word</Application>'
    '<Pages>1</Pages><Words>29890</Words><Characters>164400</Characters>'
    '<Paragraphs>387</Paragraphs></Properties>'
)

RSIDS = ('<w:rsids><w:rsidRoot w:val="00B47730"/><w:rsid w:val="00FC693F"/>'
         '<w:rsid w:val="00E618BF"/></w:rsids>')
DOC_IDS = ('<w14:docId w14:val="2A1B3C4D"/>'
           '<w15:docId w15:val="7F1E2D3C-4B5A-6978-8C9D-0E1F2A3B4C5D"/>')

STAMP = (2026, 9, 18, 2, 30, 6)  # fecha 'sucia' de las entradas del ZIP


def patch_document(text):
    # posiciones sobre el texto original; se inserta de derecha a izquierda
    p_open = text.index('<w:p>')
    ppr_open = text.index('<w:pPr>')
    rpr_open = text.index('<w:rPr>')
    rpr_close = text.index('</w:rPr>', rpr_open)
    ppr_close = text.index('</w:pPr>', ppr_open)
    p_close = text.index('</w:p>')
    for pos, chunk in sorted([
        (p_close, COMMENT_ANCHOR_END),
        (ppr_close + len('</w:pPr>'), COMMENT_ANCHOR_START + INS + DEL),
        (ppr_close, PPR_CHANGE),
        (rpr_close, RPR_CHANGE),
        (p_open + len('<w:p'), ' w14:paraId="12345678" w14:textId="9ABCDEF0"'
                               ' w:rsidR="00FC693F" w:rsidRDefault="00E618BF"'),
    ], reverse=True):
        text = text[:pos] + chunk + text[pos:]
    return text


def patch_settings(text):
    text = text.replace('</w:compat>', '</w:compat>' + RSIDS)
    text = text.replace('</w:settings>', DOC_IDS + '</w:settings>')
    # trackRevisions después de proofState
    i = text.index('>', text.index('<w:proofState')) + 1
    text = text[:i] + '<w:trackRevisions/>' + text[i:]
    return text


def add_rel(text, rel):
    return text.replace('</Relationships>', rel + '</Relationships>')


def add_override(text, override):
    return text.replace('</Types>', override + '</Types>')


def main(src, dst):
    with zipfile.ZipFile(src) as zin:
        parts = [(i.filename, zin.read(i.filename)) for i in zin.infolist()]

    out = []
    for name, data in parts:
        text = data.decode('utf-8') if name.endswith(('.xml', '.rels')) else None
        if name == 'word/document.xml':
            data = patch_document(text).encode('utf-8')
        elif name == 'word/settings.xml':
            data = patch_settings(text).encode('utf-8')
        elif name == 'docProps/core.xml':
            data = CORE.encode('utf-8')
        elif name == 'docProps/app.xml':
            data = APP.encode('utf-8')
        elif name == 'word/_rels/document.xml.rels':
            text = add_rel(text, '<Relationship Id="rId98" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/comments" Target="comments.xml"/>')
            text = add_rel(text, f'<Relationship Id="rId97" Type="http://schemas.microsoft.com'
                                f'/office/2011/relationships/people" Target="people.xml"/>')
            data = text.encode('utf-8')
        elif name == '_rels/.rels':
            text = add_rel(text, '<Relationship Id="rId4" Type="http://schemas.openxmlformats.org'
                                 '/officeDocument/2006/relationships/custom-properties"'
                                 ' Target="docProps/custom.xml"/>')
            data = text.encode('utf-8')
        elif name == '[Content_Types].xml':
            for part, ctype in [
                ('/word/comments.xml', 'application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml'),
                ('/word/people.xml', 'application/vnd.openxmlformats-officedocument.wordprocessingml.people+xml'),
                ('/docProps/custom.xml', 'application/vnd.openxmlformats-officedocument.custom-properties+xml'),
            ]:
                text = add_override(text, f'<Override PartName="{part}" ContentType="{ctype}"/>')
            data = text.encode('utf-8')
        out.append((name, data))

    out.append(('word/comments.xml', COMMENTS.encode('utf-8')))
    out.append(('word/people.xml', PEOPLE.encode('utf-8')))
    out.append(('docProps/custom.xml', CUSTOM.encode('utf-8')))

    with zipfile.ZipFile(dst, 'w', zipfile.ZIP_DEFLATED) as zout:
        for name, data in out:
            info = zipfile.ZipInfo(name, date_time=STAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            zout.writestr(info, data)
    print('fixture sucio:', dst, '|', len(out), 'partes')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
