#!/usr/bin/env python3
"""Genera un .xlsx de prueba 'sucio': propiedades, propiedades personalizadas,
comentario con autor, lista de personas con cuenta, conexión a base de datos,
enlaces a otros libros, configuración de impresora, miniatura y hoja muy oculta.
Uso: make_fixture_xlsx.py salida.xlsx
"""
import sys
import zipfile

from openpyxl import Workbook
from openpyxl.comments import Comment
from openpyxl.workbook.defined_name import DefinedName

SS = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main'
THREADED = 'http://schemas.microsoft.com/office/spreadsheetml/2018/threadedcomments'
CT_NS = 'http://schemas.openxmlformats.org/package/2006/content-types'
RELS_NS = 'http://schemas.openxmlformats.org/package/2006/relationships'

CORE = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"'
    ' xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/"'
    ' xmlns:dcmitype="http://purl.org/dc/dcmitype/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
    '<dc:title>Estado de cuenta clientes</dc:title>'
    '<dc:subject>Conciliaci\u00f3n mensual</dc:subject>'
    '<dc:creator>Ariadna Betsab\u00e9 Mart\u00ednez Andrade</dc:creator>'
    '<cp:keywords>clientes, conciliaci\u00f3n</cp:keywords>'
    '<dc:description>generated by openpyxl</dc:description>'
    '<cp:lastModifiedBy>ari martinez</cp:lastModifiedBy>'
    '<cp:revision>14</cp:revision>'
    '<dcterms:created xsi:type="dcterms:W3CDTF">2026-09-18T00:17:00Z</dcterms:created>'
    '<dcterms:modified xsi:type="dcterms:W3CDTF">2026-09-18T02:16:00Z</dcterms:modified>'
    '</cp:coreProperties>'
)

APP = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"'
    ' xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
    '<Template>Normal.xltm</Template><TotalTime>41</TotalTime>'
    '<Company>Despacho Jur\u00eddico X</Company><Manager>Ariadna Mart\u00ednez</Manager>'
    '<Application>Microsoft Excel</Application><AppVersion>16.0300</AppVersion>'
    '</Properties>'
)

CUSTOM = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    '<Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/custom-properties"'
    ' xmlns:vt="http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes">'
    '<property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="2" name="_AuthorEmail">'
    '<vt:lpwstr>ari@ejemplo.com</vt:lpwstr></property>'
    '<property fmtid="{D5CDD505-2E9C-101B-9397-08002B2CF9AE}" pid="3" name="Cliente">'
    '<vt:lpwstr>Telcel</vt:lpwstr></property></Properties>'
)

CONNECTIONS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    f'<connections xmlns="{SS}">'
    '<connection id="1" name="Consultas" type="5" refreshedVersion="8" background="1">'
    '<dbPr connection="DRIVER={SQL Server};SERVER=SRV01;UID=sa;PWD=hunter2;DATABASE=Clientes"'
    ' command="SELECT * FROM saldos" connectionType="2"/>'
    '</connection></connections>'
)

PERSONS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    f'<personList xmlns="{THREADED}">'
    '<person displayName="Ariadna Mart\u00ednez" id="{11111111-2222-3333-4444-555555555555}"'
    ' userId="bbf90fce0664e5a7" providerId="Windows Live"/>'
    '<person displayName="ari martinez" id="{66666666-7777-8888-9999-000000000000}"'
    ' userId="04293925dad62832" providerId="Windows Live"/></personList>'
)

EXTERNAL_LINK = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    f'<externalLink xmlns="{SS}"><externalBook>'
    '<sheetNames><sheetName val="Saldos"/></sheetNames></externalBook></externalLink>'
)

EXTERNAL_RELS = (
    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
    f'<Relationships xmlns="{RELS_NS}">'
    '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/'
    'relationships/externalLinkPath" Target="C:\\Users\\joz\\Documents\\clientes.xlsx"'
    ' TargetMode="External"/></Relationships>'
)

THUMB = b'\x89PNG\r\n\x1a\n' + b'\x00' * 64


def make_base(path):
    wb = Workbook()
    ws = wb.active
    ws.title = 'Saldos'
    ws['A1'] = 'Cliente'
    ws['B1'] = 'Saldo'
    ws['A2'] = 'Telcel'
    ws['B2'] = 1500
    ws['A1'].comment = Comment('Revisar este saldo antes de enviar.', 'Ariadna Mart\u00ednez')
    hidden = wb.create_sheet('Notas internas')
    hidden['A1'] = 'no borrar: usado por la macro'
    hidden.sheet_state = 'veryHidden'
    wb.defined_names.add(DefinedName('SaldosExternos', attr_text="[1]Saldos!$A$1:$B$2"))
    wb.save(path)


def patch(path):
    with zipfile.ZipFile(path) as z:
        parts = [(i.filename, z.read(i.filename)) for i in z.infolist()]

    extra = [
        ('docProps/core.xml', CORE.encode('utf-8')),
        ('docProps/app.xml', APP.encode('utf-8')),
        ('docProps/custom.xml', CUSTOM.encode('utf-8')),
        ('docProps/thumbnail.png', THUMB),
        ('xl/connections.xml', CONNECTIONS.encode('utf-8')),
        ('xl/persons/person.xml', PERSONS.encode('utf-8')),
        ('xl/externalLinks/externalLink1.xml', EXTERNAL_LINK.encode('utf-8')),
        ('xl/externalLinks/_rels/externalLink1.xml.rels', EXTERNAL_RELS.encode('utf-8')),
        ('xl/printerSettings/printerSettings1.bin', b'\x00\x01\x02\x03'),
    ]
    added = {n: d for n, d in extra}

    out = []
    for name, data in parts:
        text = data.decode('utf-8') if name.endswith(('.xml', '.rels')) else None
        if name in added:
            continue
        if name == '_rels/.rels':
            text = text.replace('</Relationships>',
                                '<Relationship Id="rIdC" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/custom-properties"'
                                ' Target="docProps/custom.xml"/>'
                                '<Relationship Id="rIdT" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/thumbnail"'
                                ' Target="docProps/thumbnail.png"/></Relationships>')
            data = text.encode('utf-8')
        elif name == 'xl/_rels/workbook.xml.rels':
            text = text.replace('</Relationships>',
                                '<Relationship Id="rIdConn" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/connections"'
                                ' Target="connections.xml"/>'
                                '<Relationship Id="rIdPers" Type="http://schemas.microsoft.com/office'
                                '/2017/relationships/person" Target="persons/person.xml"/>'
                                '<Relationship Id="rIdExt" Type="http://schemas.openxmlformats.org'
                                '/officeDocument/2006/relationships/externalLink"'
                                ' Target="externalLinks/externalLink1.xml"/></Relationships>')
            data = text.encode('utf-8')
        elif name == '[Content_Types].xml':
            for part, ctype in [
                ('/docProps/custom.xml',
                 'application/vnd.openxmlformats-officedocument.custom-properties+xml'),
                ('/docProps/thumbnail.png', 'image/png'),
                ('/xl/connections.xml',
                 'application/vnd.openxmlformats-officedocument.spreadsheetml.connections+xml'),
                ('/xl/persons/person.xml',
                 'application/vnd.ms-excel.person+xml'),
                ('/xl/externalLinks/externalLink1.xml',
                 'application/vnd.openxmlformats-officedocument.spreadsheetml.externalLink+xml'),
                ('/xl/printerSettings/printerSettings1.bin',
                 'application/vnd.openxmlformats-officedocument.spreadsheetml.printerSettings'),
            ]:
                text = text.replace('</Types>',
                                    f'<Override PartName="{part}" ContentType="{ctype}"/></Types>')
            data = text.encode('utf-8')
        out.append((name, data))

    out.extend(added.items())

    with zipfile.ZipFile(path, 'w', zipfile.ZIP_DEFLATED) as zout:
        for name, data in out:
            info = zipfile.ZipInfo(name, date_time=(2026, 9, 18, 2, 30, 6))
            info.compress_type = zipfile.ZIP_DEFLATED
            zout.writestr(info, data)


if __name__ == '__main__':
    make_base(sys.argv[1])
    patch(sys.argv[1])
    print('fixture xlsx:', sys.argv[1])
